### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by besnardb** [dendenxu/fast-gaussian-rasterization#5]
Hi, I got the following error : 

`Traceback (most recent call last):
  File "/render.py"
    rasterizer = GaussianRasterizer(raster_settings=raster_settings)
  File "/fast_gaussian_rasterization/fast_gauss/__init__.py", line 39, in __init__
    raster_context = GSplatContextManager(init_buffer_size=init_buffer_size, init_texture_size=init_texture_size, dtype=dtype, tex_dtype=tex_dtype)  # only created once
  File "/fast_gaussian_rasterization/fast_gauss/gsplat_utils.py", line 63, in __init__
    self.resize_buffers(init_buffer_size)
  File "/fast_gaussian_rasterization/fast_gauss/gsplat_utils.py", line 247, in resize_buffers
    self.init_gl_buffers(self.max_verts)
  File "/fast_gaussian_rasterization/fast_gauss/gsplat_utils.py", line 184, in init_gl_buffers
    raise e
  File "/fast_gaussian_rasterization/fast_gauss/gsplat_utils.py", line 177, in init_gl_buffers
    self.cu_vbo = CHECK_CUDART_ERROR(cudart.cudaGraphicsGLRegisterBuffer(self.vbo, flags))
  File "/fast_gaussian_rasterization/fast_gauss/cuda_utils.py", line 93, in CHECK_CUDART_ERROR
    raise RuntimeError(FORMAT_CUDART_ERROR(err))
RuntimeError: cudaErrorOperatingSystem(304): OS call failed or operation not supported on this OS
`

Environment Details:

- **Driver Version**: `550.54.15`
- **Docker Image**: `nvidia/cuda:11.6.2-devel-ubuntu20.04`
- **CUDA Toolkit**: `11.6`

Could you please provide information about the environment used ?

**Comment by dendenxu** [comment]
Hi, thanks for using our code.
The rasterizer is tested on native Windows and Ubuntu. 
However, in my previous experience on other projects, the CUDA-GL interop should work fine on docker-based environments (at least for offline rendering). Thus this might be a usage issue. Could you provide more details, for example is your machine connected to a display, or are you using any Graphical forwarding (X11?) if this is a remote server?

**Comment by besnardb** [comment]
I'm currently using offline rendering and the issue seems to occur at the beginning : `raster_context = GSplatContextManager(init_buffer_size=init_buffer_size, init_texture_size=init_texture_size, dtype=dtype, tex_dtype=tex_dtype)` line 39 of `__init__.py` file. 

Could it be that some required packages are missing in my environment?
Do you have a list of packages used for offline rendering?

**Comment by dendenxu** [comment]
The required packages should have already been installed if you've run `pip install -r requirements.txt` without problems. In this situation, could you try running this test: https://github.com/zju3dv/EasyVolcap/blob/main/tests/headless_opengl_tests.py and check whether any error occurs? Note that since we're only testing the OpenGL environment, there's no need to install extra dependencies:

```shell
git clone https://github.com/zju3dv/EasyVolcap
cd EasyVolcap
pip install -e . --no-build-isolation --no-deps
python tests/headless_opengl_tests.py # maybe install missing packages if any fatal errors are reported
```
